"""
Sprint 5 - Day 33
Company Ranking Generator

Consumes:
    output/company_summaries.csv

Produces:
    output/company_rankings.csv

Purpose:
    Rank NIFTY100 companies using the normalized investment score
    generated by the Day 32 company summary pipeline.

No new financial metrics are calculated here.
The ranking layer only organizes and ranks the existing NLP-derived
company-level signals.
"""

from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd


# ---------------------------------------------------------------------
# PATHS
# ---------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[2]

INPUT_FILE = PROJECT_ROOT / "output" / "company_summaries.csv"
OUTPUT_FILE = PROJECT_ROOT / "output" / "company_rankings.csv"


# ---------------------------------------------------------------------
# LOGGING
# ---------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------
# CONSTANTS
# ---------------------------------------------------------------------

REQUIRED_COLUMNS = [
    "company_id",
    "sentiment",
    "pro_count",
    "con_count",
    "pro_score",
    "con_score",
    "net_score",
    "normalized_score",
    "strongest_pro_rule",
    "strongest_pro_confidence",
    "strongest_con_rule",
    "strongest_con_confidence",
    "investment_summary",
]


SENTIMENT_PRIORITY = {
    "Strong Positive": 5,
    "Positive": 4,
    "Neutral": 3,
    "Negative": 2,
    "Strong Negative": 1,
}


# ---------------------------------------------------------------------
# VALIDATION
# ---------------------------------------------------------------------

def validate_input(df: pd.DataFrame) -> None:
    """Validate the Day 32 company summary dataset."""

    missing_columns = [
        column for column in REQUIRED_COLUMNS
        if column not in df.columns
    ]

    if missing_columns:
        raise ValueError(
            f"Missing required columns: {missing_columns}"
        )

    if df.empty:
        raise ValueError("Input dataset is empty.")

    if df["company_id"].isna().any():
        raise ValueError("company_id contains NULL values.")

    if df["company_id"].duplicated().any():
        duplicates = df.loc[
            df["company_id"].duplicated(),
            "company_id",
        ].tolist()

        raise ValueError(
            f"Duplicate company_id values found: {duplicates}"
        )

    if df["normalized_score"].isna().any():
        raise ValueError(
            "normalized_score contains NULL values."
        )

    if df["sentiment"].isna().any():
        raise ValueError(
            "sentiment contains NULL values."
        )

    logger.info(
        "Input validation passed: %d companies",
        len(df),
    )


# ---------------------------------------------------------------------
# RANKING
# ---------------------------------------------------------------------

def create_rankings(df: pd.DataFrame) -> pd.DataFrame:
    """
    Create the company ranking dataset.

    Primary ranking:
        normalized_score descending

    Secondary ranking:
        net_score descending

    Additional tie-breakers:
        pro_count descending
        con_count ascending
        sentiment priority descending
        company_id ascending
    """

    ranked = df.copy()

    # Ensure numeric fields are numeric.
    numeric_columns = [
        "pro_count",
        "con_count",
        "pro_score",
        "con_score",
        "net_score",
        "normalized_score",
        "strongest_pro_confidence",
        "strongest_con_confidence",
    ]

    for column in numeric_columns:
        ranked[column] = pd.to_numeric(
            ranked[column],
            errors="coerce",
        )

    if ranked[numeric_columns].isna().any().any():
        bad_columns = ranked[numeric_columns].columns[
            ranked[numeric_columns].isna().any()
        ].tolist()

        raise ValueError(
            f"Invalid numeric values found in columns: {bad_columns}"
        )

    # Add sentiment priority strictly for ranking tie-breaking.
    ranked["_sentiment_priority"] = (
        ranked["sentiment"]
        .map(SENTIMENT_PRIORITY)
        .fillna(0)
    )

    # Sort by the existing investment score first.
    ranked = ranked.sort_values(
        by=[
            "normalized_score",
            "net_score",
            "pro_count",
            "con_count",
            "_sentiment_priority",
            "company_id",
        ],
        ascending=[
            False,
            False,
            False,
            True,
            False,
            True,
        ],
        kind="mergesort",
    ).reset_index(drop=True)

    # Assign final ranking position.
    ranked.insert(
        0,
        "rank",
        range(1, len(ranked) + 1),
    )

    # Remove internal helper column.
    ranked = ranked.drop(
        columns=["_sentiment_priority"]
    )

    return ranked


# ---------------------------------------------------------------------
# OUTPUT VALIDATION
# ---------------------------------------------------------------------

def validate_output(df: pd.DataFrame) -> None:
    """Validate the generated ranking dataset."""

    expected_rows = 92

    if len(df) != expected_rows:
        raise ValueError(
            f"Expected {expected_rows} companies, "
            f"but generated {len(df)}."
        )

    if df["rank"].tolist() != list(range(1, expected_rows + 1)):
        raise ValueError(
            "Rank column is not a continuous sequence from 1 to 92."
        )

    if df["company_id"].duplicated().any():
        raise ValueError(
            "Duplicate companies found in ranking output."
        )

    if df["normalized_score"].isna().any():
        raise ValueError(
            "Ranking output contains NULL normalized_score values."
        )

    # Confirm descending score order.
    scores = df["normalized_score"].tolist()

    if any(
        scores[index] < scores[index + 1]
        for index in range(len(scores) - 1)
    ):
        raise ValueError(
            "Ranking order is invalid: normalized_score is not "
            "sorted in descending order."
        )

    logger.info(
        "Output validation passed: %d ranked companies",
        len(df),
    )


# ---------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------

def main() -> None:
    logger.info("=" * 70)
    logger.info("SPRINT 5 - DAY 33 - COMPANY RANKING GENERATOR")
    logger.info("=" * 70)

    logger.info("Loading: %s", INPUT_FILE)

    if not INPUT_FILE.exists():
        raise FileNotFoundError(
            f"Required input file not found: {INPUT_FILE}"
        )

    df = pd.read_csv(INPUT_FILE)

    logger.info(
        "Loaded %d company summaries",
        len(df),
    )

    # Validate Day 32 output.
    validate_input(df)

    # Generate ranking.
    ranked_df = create_rankings(df)

    logger.info(
        "Rankings generated: %d",
        len(ranked_df),
    )

    # Validate final ranking.
    validate_output(ranked_df)

    # Save output.
    ranked_df.to_csv(
        OUTPUT_FILE,
        index=False,
    )

    # Display ranking summary.
    logger.info("")
    logger.info("Top 10 companies:")

    for _, row in ranked_df.head(10).iterrows():
        logger.info(
            "  %2d. %-15s | Score: %7.2f | Sentiment: %s",
            int(row["rank"]),
            row["company_id"],
            float(row["normalized_score"]),
            row["sentiment"],
        )

    logger.info("")
    logger.info("=" * 70)
    logger.info("SPRINT 5 - DAY 33 COMPLETE")
    logger.info("=" * 70)
    logger.info(
        "Companies ranked:       %d",
        len(ranked_df),
    )
    logger.info(
        "Highest score:          %.2f",
        ranked_df["normalized_score"].max(),
    )
    logger.info(
        "Lowest score:           %.2f",
        ranked_df["normalized_score"].min(),
    )
    logger.info(
        "Created:                %s",
        OUTPUT_FILE,
    )
    logger.info(
        "Verification:           PASS"
    )
    logger.info("=" * 70)


if __name__ == "__main__":
    main()